<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/2/27
 * Time: 16:21
 */
namespace app\admin\controller;
use think\auth\Auth;
use think\Controller;
use think\Request;
use think\Session;

class Base extends Controller{
    protected $request;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->request = Request::instance();
        $adminId = Session::get('adminId');
        if (!$adminId){
            $this->error('请您先登陆！','Login/login');
        }
        $this->checkAuth();
    }
    /*方法以小驼峰命名，函数以下划线命名区分*/
    public function checkAuth(){
        $module = $this->request->module();
        $controller = $this->request->controller();
        /*获取的方法自动转换为全小写*/
        $action = $this->request->action();
        /*过滤方法必须是全小写*/
        $noCheck = ['admin/Index/index','admin/Base/getinfo'];
        //$noCheck = [];
        if(!in_array($module.'/'.$controller.'/'.$action,$noCheck)){
            $auth = new Auth();
            $adminId = Session::get('adminId');
            $result = $auth->check($module.'/'.$controller.'/'.$action,$adminId);
            if(!$result){
                $this->error('对不起，您没有权限操作！');
            }
        }
    }

    /**获取初始信息
     * @return mixed
     */
    public function getInfo(){
        $userName = Session::get('userName');
        $date = date('Y年m月d日');
        $arrweek  = ['日','一','二','三','四','五','六'];
        $week = $arrweek[date('w')];

        $this->assign('userName',$userName);
        $this->assign('date',$date);
        $this->assign('week',$week);
        return $this->fetch();
    }

}