<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/2/27
 * Time: 16:20
 */
namespace app\admin\controller;
use think\Db;
use think\Session;

class Index extends Base{
    protected $request;
    public function index()
    {
        $userName = Session::get('userName');
        $this->assign('userName',$userName);
        return $this->fetch(); // TODO: Change the autogenerated stub
    }


}